"""add Department

Revision ID: 34151f8e7ab4
Revises: debff40e5af9
Create Date: 2023-12-20 10:23:18.892900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34151f8e7ab4'
down_revision = 'debff40e5af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
